apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
   app: my-app
   env: devops
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
         containerPort:  80  
---
