apiVersion: v1
kind: Pod
metadata:
  name: mypod-1
  labels:
    app: demo
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
         containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
  labels:
    app: demo
spec:
  containers:
    - name: httpd-container
      image: httpd
      ports:
        containerPort: 80
