apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc
  labels:
    app: my-replica
spec:
  replicas: 3
  selector:
    app: my-app-1
  template:
    metadata:
      name: my-pod1
      labels:
        app: my-app-1
        env: devops
    spec:
      containers:
        - name: nginx
          image: nginx     
          ports:
          - name: http
            containerPort: 80

