apiVersion: v1
kind: Service
metadata:
  name: my-svc-node
  labels:
    app: my-svc-node
    env: devops
spec:
  type: NodePort
  selector: 
    app: myapp
  ports:
    - name:
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: pod2-app-svc
spec:
  type: LoadBalancer
  selector: 
    name: pod2-app
    app: pos2-app
    ports:
    - name: httpd
     protocol: TCP
     port: 80
     targetPort: 80
