apiVersion: v1
kind: Service
metadata:
  name: my-svc-node
  labels:
    app: my-svc-node
    env: devops
spec:
  type: NodePort
  selector: 
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pod2-app-svc
spec:
  type: LoadBalancer
  selector: 
    app: pod2-app
  ports:
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 80
