FROM alpine:latest


RUN apk update && apk add --no-cache apache2
ADD https://downloads.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz.asc /opt

ENV project=devops


WORKDIR /var/www/localhost/htdocs/


COPY index.html .


EXPOSE 80


CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]